package com.github.gongfuboy.company.sql.creater.pojo

object TOrganization {
}

/**
  * Autogenerated by Dapeng-Code-Generator (2.0.0)
  *
  * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
  *  @generated

  *
  **/
case class TOrganization(

                          /**
                            *id
                            **/

                          id : Int, /**
                            *父组织id
                            **/

                          parentId : Int, /**
                            *组织名称
                            **/

                          name : String, /**
                            *代码(无用)
                            **/

                          code : String, /**
                            *组织类型(无用)
                            **/

                          `type` : Int, /**
                            *状态 0：正常 1：禁用
                            **/

                          disable : Int, /**
                            *是否为利润中心 0:未定义 1: 是 2：否
                            **/

                          isProfitCenter : Int, /**
                            *所属利润中心，当为利润中心时，则是自身id，否则为对应组织id
                            **/

                          profitCenterId : Int, /**
                            *区域  0:未定义 1：华南 2：华东
                            **/

                          region : Int
                        )
      